language: python
sudo: false

env:
  global:
    # Doctr deploy key for xpdAcq/SHED-sidewinder
    - secure: "RuTv22W0qeK9N2i8MFHaT6EilLIsSCo3d7NvreG0DHKMSDY9HDC3a5TLqy8z6BhaAts7IhLnHV0HmLolwLBFOoaj6FV/uD8eZwSMsOoCjaotvGfkf+ULlIUqjbdDPd424VonKV1Ezy+rl/6SiPta/cus0utRnZOZ08x+EGXfoiziXdNZygiMSdnsxAY2x6imcM26pTXa4nwXl3O6WQ4oyzAYlt/V1ic6Y7WCDLE+W3P+5MItAgy9SLnd+ifosKvU9hrBizGn5IB4akxGR5bAInQIO6pX83nDwWJBYIJuROQm5Zutmd0MgmvXd/alk+ioXsad+bGLgwbFcB+GM/j/sX/XP2MBygA9QAQESHokw1YAdM9hR+RngR/beSk4UfEmIBdZLfNt29Fi/c2vVFZt4Kfxcaoeb8U+su8X9xXZ5U0KIqijUYO2YoqHdBiPtmtBoX/2tVgyQaEXpSeOAXzVSpbn2uqlS+QH8qIncxVynKNbYwM4XqO4S19ENfz+PB+MXC9rWuHtE760c/BzLFNumXFxfVtLnbtUoBSE/0IUHnLlO/w4CIKk9e90i7vzhdA1Rv+/OWHJ/sRWxklYBhuhsmToSC57liVVtw5rN+jEKVcMItdB3RRrbXweopnDU2LjTgobmrjAGC0QRT5wWKr8PS8v0EUYnMhbUUBWNCf1diM="


services:
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
matrix:
  include:
    - python: 3.6

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "export DISPLAY=:99.0"
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/mc
  - export PATH=~/mc/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no --set quiet true
  - conda config --add channels conda-forge
  - conda update conda --yes

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda create --yes -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes --file requirements/build.txt
  - conda install pip
  - pip install -r requirements/pip.txt
  - pip install .


script:
  - conda install --file requirements/run.txt
  - conda install --yes --file requirements/test.txt
  - pip install codecov pytest-env
  - coverage run run_tests.py
  - coverage report -m
  - codecov
  - sidewind -h
  - sidewind init test .
  - sidewind nomad -h
  - flake8 shed_sidewinder
  - conda install --yes --file requirements/docs.txt
  - pip install git+git://github.com/drdoctr/doctr.git
  - cd docs
  - make html
  - cd ..
  - doctr deploy . --built-docs ./docs/_build/html;