language: python
sudo: false

env:
  global:
    # Doctr deploy key for xpdAcq/sidewinder-spec
    - secure: "CV3jgQDEbVRB9Ey+BUdLS1qn1YCJ/BjizcTB5j0lmtV8K0QhbfGzzTlNtrsrAgCxXm9FahM7+ghbs7Ya2eZLytFwekVpHLxm0lMRgQF5QwFsL91JZgqxBVYzvQgR1lWbr3is22ZipMDJYAnkzqhNSPku7jLcE0GpwzfMfHryHvyGKmjKpSr3GKtRRFzj8v5YwbzI+sX6HE1V2NOV4Xu5q9b65hMU9KWQifxTMxB4FiBA/NEnZWay4IehotWcyao8PgniRYFNEwLR2r1xooZsqP6J9J7w6lL95Wg0Oc4PS0a2XAwJYWlslgngnWWvxzeZgxn1l4M9lUZSYe5Yq+++EX+n7asW1vxohsjPEvaMb6CuLEgvedYA/gNRuY8onI0lQ3D2Nez4ZO3u4dbEwUNTek7yfVHdLOBdh1lyVLnOUPP9kviApkfWb6EcNPE2Xwy+Qp7ibfurSF5yjuZp8ZJ/M4UwaMwWrRtr5muxZRtchdBkPYuGv+NQM7/5Q67IeeAiYfxxvM/LVXJn+pfbDCWGhUTZfPLYiSNR7+QUeelsszSmRAeNW4gbXzivNa80AGCx+0MvfAK4TXWNGYNcAUiYtQA4e8ycae7EZ3h/DPvECL1b9EPcb0K2UXLQe3LZfRszjinStFQnzTMndqjyjzJB7fJwW1gHEhKjgaPLUnyRCYI="


services:
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
matrix:
  include:
    - python: 3.6

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "export DISPLAY=:99.0"
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/mc
  - export PATH=~/mc/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no --set quiet true
  - conda config --add channels conda-forge
  - conda update conda --yes

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda create --yes -n testenv python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  - conda install --yes --file requirements/build.txt
  - conda install pip
  - pip install -r requirements/pip.txt
  - pip install .


script:
  - conda install --file requirements/run.txt
  - conda install --yes --file requirements/test.txt
  - pip install codecov pytest-env
  - coverage run run_tests.py
  - coverage report -m
  - codecov
  - sidewind -h
  - sidewind init test .
  - sidewind nomad -h
  - flake8 shed_sidewinder
  - conda install --yes --file requirements/docs.txt
  - pip install git+git://github.com/drdoctr/doctr.git
  - cd docs
  - make html
  - cd ..
  - doctr deploy . --built-docs ./docs/_build/html;